title: "Michael R Peck Jr - Portfolio"
name: "Michael R Peck Jr"
description: "My Professional ePortfolio"
remote_theme: mmistakes/minimal-mistakes
site_author: "Michael R Peck Jr"

# Plugins necessary for remote theme
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Sidebar configuration
author:
  name   : "Michael R Peck Jr"
  avatar : "https://github.com"
  bio    : "Aspiring Full-Stack Developer. Welcome to my Portfolio.<br><br>🎓 '26 B.S. Computer Science (SE)<br>🎓 '19 B.S. Game Programming & Dev"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peck2703"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com"
    - label: "Facebook"
      icon: "fas fa-fw fa-facebook"
      url: "https://www.facebook.com/Onewingedangel2703"
    - label: "itch.io - Games"
      icon: "fas fa-fw fa-gamepad"
      url:  "https://peck2703.itch.io/"

# Core settings for this specific theme
locale: "en-US"
defaults:
  - scope:
      path: ""
    values:
      layout: "single" # Tells the theme to use its default page wrapper
      author_profile: true # Puts your profile card on the sidebar
site_navigation:  main

# Force the site to look at stylesheet
stylesheets:
  - /assets/css/main.scss

