title: Michael R Peck Jr - Portfolio
remote_theme: mmistakes/minimal-mistakes@4.24.4

# Core settings for this specific theme
locale: "en-US"
defaults:
  - scope:
      path: ""
    values:
      layout: "single" # Tells the theme to use its default page wrapper
      author_profile: true # Puts your profile card on the sidebar
